global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'local_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9100']
#  - job_name: 'servers'
#    file_sd_configs:
#      - files:
#          - /service-discovery/servicediscovery.json
#        refresh_interval: 10s